server:
  port: 80

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/pd_store?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
        
    data:
      solr:   #注意修改ip地址
        host: http://192.168.74.137:8983/solr/pd
    rabbitmq:
      host: 192.168.74.135
      port: 5672
      virtualHost: /pd
      username: admin
      password: admin
    
    
mybatis:
  #typeAliasesPackage: cn.tedu.ssm.pojo
  mapperLocations: classpath:com.pd.mapper/*.xml

logging:
  level: 
    cn.tedu.ssm.mapper: debug
resources: # 指定静态资源的路径
        static-locations: classpath:/
        cache-period: 0